### ISSUE TITLE
services edit/update

### ISSUE THREAD

**Issue by janelbrandon** [loui7/services-portal#17]
@loui7 and @vivecuervo7 

I've been working with @vicnatacu on automated testing, and we found a small issue. When you edit an object and update, you don't need to pass the id of the object through the form - it will come through parameters directly. So:
1. in views/services/edit.html.erb, you can remove the hidden id field 
2. In the services controller update action, instead of getting the id from params[:service][:id], it should come directly from params[:id]

The way it is works - but it is unconventional and not best practice. It is causing an automated test to fail.

Vic can make this change if that's ok with the two of you.

**Comment by vicnatacu** [comment]
If Louis and Isaac agree I am happy to make these changes.

**Comment by vicnatacu** [comment]
Sorry Isaac and Louis, as you guy did see this message and I needed to update this so I progress with respec fixes and testing. I am raising a pull request for another branch that only has this change. Please review ASAP.
